const fs=require('fs');const vm=require('node:vm');const assert=require('node:assert/strict');
let passed=0;const check=(ok,label)=>{assert(ok,label);passed++;console.log('OK '+label)};const flush=()=>new Promise(r=>setImmediate(r));
(async()=>{
for(const name of ['player.js','editor.js']){
const source=fs.readFileSync(require('node:path').join(__dirname,'../assets',name),'utf8');const api=source.slice(source.indexOf('async function api('),source.indexOf(name==='editor.js'?'const saveTimers':'async function serverRunner('));const runner=source.slice(source.indexOf('async function serverRunner('),source.indexOf(name==='editor.js'?"$('#tabs').querySelectorAll('button').forEach(b=>b.onclick=":"const slug=location.pathname"));
const elements={};const make=()=>({addEventListener(event,fn){this[event]=fn},disabled:false,textContent:''});const root={innerHTML:'',querySelector(s){return elements[s]??=make()},querySelectorAll(){return[]}};const calls=[];let next={id:'session',version:0,kind:'text',title:'Conte sua situação',description:'Explique',maxLength:2000,color:'#6c46ed',brand:'ADV',canBack:false};let failure=false;
const ctx={document:{querySelector:()=>root},AbortController,setTimeout,clearTimeout,fetch:async(url,opts)=>{calls.push({url,body:opts.body&&JSON.parse(opts.body)});return {ok:!failure,status:failure?400:200,json:async()=>failure?{error:'Texto inválido'}:next}}};vm.createContext(ctx);vm.runInContext(source.split('\n')[0]+'\n'+api+runner+'\nglobalThis.run=serverRunner;',ctx);
await ctx.run(root,'quiz-2',name==='player.js'?'public':'test');check(root.innerHTML.includes('textarea')&&root.innerHTML.includes('maxlength="2000"'),name+' mostra resposta longa limitada');
const input={elements:{answer:{value:'Minha resposta\ncom duas linhas'}}};next={...next,version:1,kind:'lead',title:'Contato',consent:'Aceito',privacy:''};elements['#text-answer'].submit({preventDefault(){},target:input});await flush();check(calls.at(-1).body.text===input.elements.answer.value&&!('score' in calls.at(-1).body),name+' envia texto intacto sem calcular pontos');check(root.innerHTML.includes('id="lead"'),name+' renderiza próxima etapa do servidor');
failure=false;next={...next,kind:'text',version:0};await ctx.run(root,'quiz-2',name==='player.js'?'public':'test');failure=true;elements['#text-answer'].submit({preventDefault(){},target:input});await flush();check(elements['#run-error'].textContent==='Texto inválido'&&root.innerHTML.includes('id="text-answer"'),name+' preserva formulário ao rejeitar resposta');
}
const source=fs.readFileSync(require('node:path').join(__dirname,'../assets/editor.js'),'utf8');const elements={'#leads-dialog':{open:true},'#leads-body':{innerHTML:''},'#leads-title':{textContent:''}};const pending={};const ctx={document:{querySelector:s=>elements[s]},quizzes:[{id:'one',name:'Primeiro'},{id:'two',name:'Segundo'}],api:url=>new Promise(resolve=>pending[url]=resolve)};vm.createContext(ctx);const end=source.indexOf("$('#view-leads').onclick=()=>");vm.runInContext(source.split('\n')[0]+'\n'+source.slice(source.indexOf('let leadsRequest=0;'),end)+'\nglobalThis.load=loadQuizLeads;',ctx);
const first=ctx.load('one'),second=ctx.load('two');pending['/api/quizzes/two/leads']({quiz:{id:'two',name:'Segundo'},total:0,leads:[]});await second;pending['/api/quizzes/one/leads']({quiz:{id:'one',name:'Primeiro'},total:1,leads:[{name:'Contato antigo'}]});await first;check(elements['#leads-title'].textContent==='Contatos — Segundo'&&elements['#leads-body'].innerHTML.includes('Nenhum contato'),'troca rápida de quiz não mistura resposta atrasada de contatos');
const loading=ctx.load('two');pending['/api/quizzes/two/leads']({quiz:{id:'two',name:'Segundo'},total:1,leads:[{id:'l',name:'Visitante',answers:[{question:'Pergunta',answer:'<img src=x onerror=alert(1)>'}]}]});await loading;check(elements['#leads-body'].innerHTML.includes('&lt;img')&&!elements['#leads-body'].innerHTML.includes('<img'),'respostas de contatos são escapadas ao exibir');
console.log(passed+' verificações de interface passaram.');
})().catch(e=>{console.error(e);process.exitCode=1});

