<?php
declare(strict_types=1);
namespace QuizAdv;
final class ApiError extends \RuntimeException {public function __construct(public int $status,string $message){parent::__construct($message);}}
final class Domain {
 public static function id():string {$b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);$h=bin2hex($b);return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20);}
 public static function uuid(mixed $v):string {if(!is_string($v)||!preg_match('/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/iD',$v))throw new ApiError(400,'Identificador inválido.');return strtolower($v);}
 public static function object(mixed $v,array $keys,array $required=[]):array {if(!is_array($v)||array_diff(array_keys($v),$keys)||array_diff($required,array_keys($v)))throw new ApiError(400,'Campos inválidos ou não permitidos.');return $v;}
 public static function text(mixed $v,int $max=1000,bool $optional=false):string {if(!is_string($v)||!preg_match('//u',$v))throw new ApiError(400,'Texto inválido.');$v=trim($v);if(class_exists('Normalizer'))$v=\Normalizer::normalize($v,\Normalizer::FORM_C);$length=function_exists('mb_strlen')?mb_strlen($v,'UTF-8'):preg_match_all('/./us',$v);if($length>$max||(!$optional&&$v==='')||preg_match('/[<>\x00-\x08\x0b\x0c\x0e-\x1f\x7f]/u',$v))throw new ApiError(400,'Revise os textos: não use HTML, campos vazios ou textos muito longos.');return $v;}
 public static function integer(mixed $v,int $min,int $max):int {if(!is_int($v)||$v<$min||$v>$max)throw new ApiError(400,'Valor numérico inválido.');return $v;}
 public static function url(mixed $v,array|null $hosts=null):string {$v=self::text($v,2000,true);if($v==='')return '';if(!filter_var($v,FILTER_VALIDATE_URL))throw new ApiError(400,'URL inválida.');$u=parse_url($v);$host=strtolower($u['host']??'');if(($u['scheme']??'')!=='https'||isset($u['user'])||isset($u['pass'])||(isset($u['port'])&&$u['port']!==443)||!str_contains($host,'.')||str_ends_with($host,'.')||filter_var($host,FILTER_VALIDATE_IP)||str_contains($host,':')||preg_match('/(?:^|\.)(localhost|local|internal|invalid|test|onion)$/',$host))throw new ApiError(400,'Use uma URL HTTPS pública, sem credenciais.');if($hosts!==null&&!in_array($host,$hosts,true))throw new ApiError(400,'O domínio do webhook precisa ser autorizado no servidor.');return $v;}
 public static function config(mixed $input,array $hosts=[]):array {$keys=['name','brand','intro','description','button','color','questions','leadTitle','leadDescription','consent','privacy','resultTitle','resultDescription','offerLabel','offerUrl','webhook','defaultResultId'];$q=self::object($input,$keys,array_diff($keys,['defaultResultId']));$out=['defaultResultId'=>isset($q['defaultResultId'])?self::uuid($q['defaultResultId']):self::id()];foreach(['name','brand','intro','button','leadTitle','resultTitle','offerLabel'] as $key)$out[$key]=self::text($q[$key],$key==='name'?120:300);foreach(['description','leadDescription','consent','resultDescription'] as $key)$out[$key]=self::text($q[$key],2000,$key!=='consent');if(!is_string($q['color'])||!preg_match('/^#[a-f0-9]{6}$/iD',$q['color']))throw new ApiError(400,'Cor inválida.');$out['color']=strtolower($q['color']);$out['privacy']=self::url($q['privacy']);$out['offerUrl']=self::url($q['offerUrl']);$out['webhook']=self::url($q['webhook'],$hosts);if(!is_array($q['questions'])||!array_is_list($q['questions'])||count($q['questions'])<1||count($q['questions'])>60)throw new ApiError(400,'Use de 1 a 60 etapas.');$seen=[$out['defaultResultId']=>true];
 $unique=function($id=null)use(&$seen){$id=$id===null?self::id():self::uuid($id);if(isset($seen[$id]))throw new ApiError(400,'Identificador repetido.');$seen[$id]=true;return $id;};$out['questions']=[];
 foreach($q['questions'] as $raw){self::object($raw,['id','type','title','options','optionIds','points','routes','next','description','duration','offerLabel','offerUrl'],['title']);$type=$raw['type']??'question';if(!in_array($type,['question','text','loading','result'],true))throw new ApiError(400,'Tipo de etapa inválido.');$s=['id'=>$unique($raw['id']??null),'type'=>$type,'title'=>self::text($raw['title'],500)];
 if($type==='question'){if(!isset($raw['options'])||!is_array($raw['options'])||!array_is_list($raw['options'])||count($raw['options'])<2||count($raw['options'])>12)throw new ApiError(400,'Use de 2 a 12 opções.');foreach(['optionIds','points','routes'] as $key)if(isset($raw[$key])&&(!is_array($raw[$key])||!array_is_list($raw[$key])||count($raw[$key])!==count($raw['options'])))throw new ApiError(400,'Opções e regras desalinhadas.');foreach($raw['options'] as $i=>$value){$s['options'][]=self::text($value,300);$s['optionIds'][]=$unique($raw['optionIds'][$i]??null);$s['points'][]=self::integer($raw['points'][$i]??0,0,100);$s['routes'][]=$raw['routes'][$i]??'';}if(isset($raw['next']))$s['next']=$raw['next'];}
 if($type==='text'){$s['description']=self::text($raw['description']??'',2000,true);$s['next']=$raw['next']??'';}
 if($type==='loading'){$s['description']=self::text($raw['description']??'',2000,true);$s['duration']=self::integer($raw['duration']??3,1,60);$s['next']=$raw['next']??'';}
 if($type==='result'){$s['description']=self::text($raw['description']??'',2000,true);$s['offerLabel']=self::text(($raw['offerLabel']??'')?:$out['offerLabel'],300);$s['offerUrl']=self::url($raw['offerUrl']??'');}$out['questions'][]=$s;}
 foreach($out['questions'] as $i=>$s){foreach(array_merge($s['routes']??[],isset($s['next'])?[$s['next']]:[]) as $target){if(!is_string($target))throw new ApiError(400,'Destino inválido.');if(in_array($target,['','lead','result'],true))continue;self::uuid($target);$position=array_search($target,array_column($out['questions'],'id'),true);if($position===false||$position<=$i)throw new ApiError(400,'O destino deve ser uma etapa posterior existente.');}}return $out;
 }
 public static function initial(string $mode,int|null $now=null):array {return ['page'=>'start','history'=>[],'answers'=>[],'pending'=>null,'captured'=>false,'enteredAt'=>$now??self::now(),'mode'=>$mode,'complete'=>false];}
 public static function now():int {return (int)floor(microtime(true)*1000);}
 public static function stage(array $q,string $id):?array {foreach($q['questions'] as $s)if($s['id']===$id)return $s;return null;}
 private static function destination(array $q,array $s,string $target):string {if($target==='lead')return 'lead';if($target==='result')return 'default';if($target!=='')return $target;$i=array_search($s['id'],array_column($q['questions'],'id'),true);return $q['questions'][$i+1]['id']??'lead';}
 private static function go(array $q,array &$state,string $to,int $now):void {if(($to==='default'||(self::stage($q,$to)['type']??'')==='result')&&!$state['captured']){$state['pending']=$to;$to='lead';}$state['history'][]=$state['page'];$state['page']=$to;$state['enteredAt']=$now;if($state['captured']&&($to==='default'||(self::stage($q,$to)['type']??'')==='result'))$state['complete']=true;}
 public static function action(array $q,array $state,mixed $input,int|null $now=null):array {$input=self::object($input,['version','action','optionId','text'],['version','action']);self::integer($input['version'],0,100000);$now??=self::now();$action=$input['action'];if(!in_array($action,['start','answer','advance','back'],true)||((isset($input['optionId'])||isset($input['text']))&&$action!=='answer'))throw new ApiError(400,'Ação inválida.');if($state['complete'])throw new ApiError(409,'Esta sessão já foi concluída.');$s=self::stage($q,$state['page']);
 if($action==='back'){if(!$state['history'])throw new ApiError(409,'Não há etapa anterior.');$to=array_pop($state['history']);unset($state['answers'][$state['page']],$state['answers'][$to]);$state['page']=$to;$state['pending']=null;$state['enteredAt']=$now;return $state;}
 if($state['page']==='start'&&$action==='start'){self::go($q,$state,$q['questions'][0]['id'],$now);return $state;}
 if(($s['type']??'')==='question'&&$action==='answer'){if(array_key_exists('text',$input))throw new ApiError(400,'Esta etapa exige uma opção.');$id=self::uuid($input['optionId']??null);$index=array_search($id,$s['optionIds'],true);if($index===false)throw new ApiError(400,'Esta opção não pertence à etapa atual.');$state['answers'][$s['id']]=$id;self::go($q,$state,self::destination($q,$s,$s['routes'][$index]?:($s['next']??'')),$now);return $state;}
 if(($s['type']??'')==='text'&&$action==='answer'){if(array_key_exists('optionId',$input))throw new ApiError(400,'Esta etapa exige uma resposta em texto.');$answer=self::text($input['text']??null,2000);$state['answers'][$s['id']]=$answer;self::go($q,$state,self::destination($q,$s,$s['next']),$now);return $state;}
 if(($s['type']??'')==='loading'&&$action==='advance'){if($now-$state['enteredAt']<$s['duration']*1000)throw new ApiError(409,'Aguarde o carregamento terminar.');self::go($q,$state,self::destination($q,$s,$s['next']),$now);return $state;}throw new ApiError(409,'Ação não permitida nesta etapa.');
 }
 public static function answers(array $q,array $state):array {$out=[];foreach($state['answers'] as $id=>$optionId){$s=self::stage($q,$id);if(($s['type']??'')==='text'){$out[]=['stageId'=>$id,'optionId'=>null,'question'=>$s['title'],'answer'=>self::text($optionId,2000),'points'=>0,'type'=>'text'];continue;}$i=$s?array_search($optionId,$s['optionIds']??[],true):false;if($i===false)throw new ApiError(500,'Resposta persistida inválida.');$out[]=['stageId'=>$id,'optionId'=>$optionId,'question'=>$s['title'],'answer'=>$s['options'][$i],'points'=>$s['points'][$i]];}return $out;}
 public static function contact(mixed $input):array {$v=self::object($input,['version','name','email','phone','consent'],['version','name','email','phone','consent']);self::integer($v['version'],0,100000);$out=['name'=>self::text($v['name'],150),'email'=>strtolower(self::text($v['email'],254)),'phone'=>preg_replace('/[() .-]/','',self::text($v['phone'],25)),'consent'=>true];if($v['consent']!==true||!filter_var($out['email'],FILTER_VALIDATE_EMAIL)||!preg_match('/^\+?\d{8,15}$/D',$out['phone']))throw new ApiError(400,'Revise o e-mail, o WhatsApp e o consentimento.');return $out;}
 public static function complete(array $q,array $state,int|null $now=null):array {if($state['page']!=='lead'||$state['captured']||$state['complete'])throw new ApiError(409,'Contato não permitido nesta etapa.');$state['captured']=true;self::go($q,$state,$state['pending']??'default',$now??self::now());return $state;}
 public static function view(string $id,int $version,array $q,array $state,int|null $now=null):array {$now??=self::now();$out=['id'=>$id,'version'=>$version,'brand'=>$q['brand'],'color'=>$q['color'],'mode'=>$state['mode'],'canBack'=>(bool)$state['history']&&!$state['complete']];$s=self::stage($q,$state['page']);if($state['page']==='start')return $out+['kind'=>'start','title'=>$q['intro'],'description'=>$q['description'],'button'=>$q['button']];if($state['page']==='lead')return $out+['kind'=>'lead','title'=>$q['leadTitle'],'description'=>$q['leadDescription'],'consent'=>$q['consent'],'privacy'=>$q['privacy']];if(($s['type']??'')==='question')return $out+['kind'=>'question','stageId'=>$s['id'],'title'=>$s['title'],'options'=>array_map(fn($label,$i)=>['id'=>$s['optionIds'][$i],'label'=>$label],$s['options'],array_keys($s['options']))];if(($s['type']??'')==='text')return $out+['kind'=>'text','stageId'=>$s['id'],'title'=>$s['title'],'description'=>$s['description'],'maxLength'=>2000];if(($s['type']??'')==='loading')return $out+['kind'=>'loading','stageId'=>$s['id'],'title'=>$s['title'],'description'=>$s['description'],'remainingMs'=>max(0,$s['duration']*1000-($now-$state['enteredAt']))];if($state['complete'])return $out+['kind'=>'result','stageId'=>$s['id']??$q['defaultResultId'],'title'=>$s['title']??$q['resultTitle'],'description'=>$s['description']??$q['resultDescription'],'offerLabel'=>$s['offerLabel']??$q['offerLabel'],'offerUrl'=>$s['offerUrl']??$q['offerUrl'],'score'=>array_sum(array_column(self::answers($q,$state),'points'))];throw new ApiError(500,'Estado inválido.');}
 public static function slug(mixed $slug):string {if(!is_string($slug)||!preg_match('/^quiz-[1-9][0-9]{0,8}$/D',$slug))throw new ApiError(400,'Endereço de quiz inválido.');return $slug;}
}

