<?php
declare(strict_types=1);
namespace QuizAdv;
final class GitHubPublisher {
 public function __construct(private array $settings,private mixed $transport=null){}
 public function configured():bool {return strlen($this->settings['GITHUB_TOKEN']??'')>10&&preg_match('/^[A-Za-z0-9_.-]+$/D',$this->settings['GITHUB_OWNER']??'')&&preg_match('/^[A-Za-z0-9_.-]+$/D',$this->settings['GITHUB_REPO']??'')&&is_string($this->settings['GITHUB_BRANCH']??null)&&strlen($this->settings['GITHUB_BRANCH'])>0;}
 private function call(string $method,string $path,array|null $body=null):array {if($this->transport)return ($this->transport)($method,$path,$body);$ch=curl_init('https://api.github.com'.$path);curl_setopt_array($ch,[CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>['Accept: application/vnd.github+json','Authorization: Bearer '.$this->settings['GITHUB_TOKEN'],'X-GitHub-Api-Version: 2026-03-10','User-Agent: QUIZ-ADV','Content-Type: application/json'],CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,encode($body));$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);if($raw===false)throw new ApiError(502,'Não foi possível conectar ao GitHub.');$json=json_decode($raw,true);if(!is_array($json))$json=[];return ['status'=>$status,'data'=>$json];}
 public function publish(string $slug,string $title):array {Domain::slug($slug);if(!$this->configured())throw new ApiError(503,'Configure o acesso do aplicativo ao GitHub na Hostinger para publicar.');$base='/repos/'.rawurlencode($this->settings['GITHUB_OWNER']).'/'.rawurlencode($this->settings['GITHUB_REPO']).'/contents/'.$slug.'/index.html';$ref=rawurlencode($this->settings['GITHUB_BRANCH']);$old=$this->call('GET',$base.'?ref='.$ref);if(!in_array($old['status'],[200,404],true))throw new ApiError(502,'Não foi possível acessar o repositório configurado.');$html=publicShell($title);$data=['message'=>'Publicar '.$slug.' pelo QUIZ ADV','branch'=>$this->settings['GITHUB_BRANCH'],'content'=>base64_encode($html)];if($old['status']===200){if(($old['data']['type']??'')!=='file'||empty($old['data']['sha']))throw new ApiError(409,'O caminho da página já está ocupado.');$existing=base64_decode(str_replace("\n",'',$old['data']['content']??''),true);if(!is_string($existing)||!str_contains($existing,'<!-- QUIZ ADV managed public page -->'))throw new ApiError(409,'Este caminho já pertence a outra página. Nenhum arquivo foi alterado.');$data['sha']=$old['data']['sha'];}
 // Reusing identical content avoids unnecessary commits; the server snapshot is published atomically below.
 if($old['status']===200&&isset($old['data']['content'])&&base64_decode(str_replace("\n",'',$old['data']['content']),true)===$html){return ['commit'=>$old['data']['sha'],'unchanged'=>true];}
 $result=$this->call('PUT',$base,$data);if(!in_array($result['status'],[200,201],true))throw new ApiError($result['status']===409?409:502,'O GitHub recusou a publicação. Confira a permissão de escrita e a branch.');$sha=$result['data']['commit']['sha']??'';if(!preg_match('/^[a-f0-9]{40,64}$/D',$sha))throw new ApiError(502,'O GitHub não confirmou a publicação.');return ['commit'=>$sha,'unchanged'=>false];}
}

