<?php
declare(strict_types=1);
namespace QuizAdv;
final class Service {
 public function __construct(private Store $db,private GitHubPublisher $github,private array $settings){}
 private function requireOwner(?string $owner):string {if(!$owner||!$this->db->one('SELECT id FROM qa_users WHERE id = ?',[$owner]))throw new ApiError(401,'Entre no editor para continuar.');return $owner;}
 private function editorQuiz(array $row):array {$p=$this->db->one('SELECT slug,active,published_at,last_error FROM qa_publications WHERE quiz_id = ? AND owner_id = ?',[$row['id'],$row['owner_id']]);return decode($row['config_json'])+['id'=>$row['id'],'_version'=>(int)$row['version'],'_publication'=>$p?['slug'=>$p['slug'],'active'=>(bool)$p['active'],'url'=>$this->settings['APP_ORIGIN'].'/'.$p['slug'],'publishedAt'=>$p['published_at'],'error'=>$p['last_error']]:null];}
 private function newSession(array $quiz,array $snapshot,string $mode,?string $visitor,?string $publication=null):array {$id=Domain::id();$state=Domain::initial($mode);$this->db->query('INSERT INTO qa_sessions (id,owner_id,quiz_id,publication_id,visitor_hash,mode,snapshot_json,state_json,version,expires_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[$id,$quiz['owner_id'],$quiz['id'],$publication,$visitor,$mode,encode($snapshot),encode($state),0,Domain::now()+86400000,Domain::now()]);return Domain::view($id,0,$snapshot,$state);}
 public function handle(string $path,string $method,array $input,?string $owner,?string $visitor):array {
 if($path==='/quizzes'){$owner=$this->requireOwner($owner);if($method==='GET')return ['quizzes'=>array_map(fn($q)=>$this->editorQuiz($q),$this->db->all('SELECT * FROM qa_quizzes WHERE owner_id = ? ORDER BY created_at DESC',[$owner]))];if($method==='POST'){Domain::object($input,['config'],['config']);$q=Domain::config($input['config'],$this->settings['WEBHOOK_HOSTS']);$id=Domain::id();$now=Domain::now();$this->db->query('INSERT INTO qa_quizzes (id,owner_id,config_json,version,created_at,updated_at) VALUES (?,?,?,?,?,?)',[$id,$owner,encode($q),1,$now,$now]);return $this->editorQuiz($this->db->quiz($id,$owner));}}
 if(preg_match('~^/quizzes/([a-f0-9-]+)(?:/(publish|sessions|leads))?$~D',$path,$m)){$owner=$this->requireOwner($owner);$q=$this->db->quiz($m[1],$owner);$tail=$m[2]??'';
  if(!$tail&&$method==='GET')return $this->editorQuiz($q);
  if(!$tail&&$method==='PUT'){Domain::object($input,['version','config'],['version','config']);$version=Domain::integer($input['version'],1,100000);$snapshot=Domain::config($input['config'],$this->settings['WEBHOOK_HOSTS']);$updated=$this->db->query('UPDATE qa_quizzes SET config_json = ?, version = version + 1, updated_at = ? WHERE id = ? AND owner_id = ? AND version = ?',[encode($snapshot),Domain::now(),$q['id'],$owner,$version]);if($updated->rowCount()!==1)throw new ApiError(409,'O quiz mudou. Recarregue para evitar perder alterações.');return $this->editorQuiz($this->db->quiz($q['id'],$owner));}
  if($tail==='sessions'&&$method==='POST'){Domain::object($input,['mode'],['mode']);if($input['mode']!=='test')throw new ApiError(400,'Use o link publicado para responder ao quiz.');return $this->newSession($q,decode($q['config_json']),'test',null);}
  if($tail==='leads'&&$method==='GET'){$rows=$this->db->all('SELECT id,name,email,phone,score,result_id,created_at,answers_json FROM qa_leads WHERE owner_id = ? AND quiz_id = ? ORDER BY created_at DESC,id DESC LIMIT 1000',[$owner,$q['id']]);foreach($rows as &$lead){$lead['answers']=decode($lead['answers_json']);unset($lead['answers_json']);}$total=$this->db->one('SELECT COUNT(*) AS total FROM qa_leads WHERE owner_id = ? AND quiz_id = ?',[$owner,$q['id']]);return ['quiz'=>['id'=>$q['id'],'name'=>decode($q['config_json'])['name']],'total'=>(int)$total['total'],'leads'=>$rows];}
  if($tail==='publish'&&$method==='POST'){Domain::object($input,['version'],['version']);$version=Domain::integer($input['version'],1,100000);if(!$this->github->configured())throw new ApiError(503,'Configure a credencial privada do GitHub na Hostinger.');$publication=$this->db->reservePublication($q['id'],$owner,$version,decode($q['config_json']));try{$receipt=$this->github->publish($publication['slug'],decode($q['config_json'])['name']);$this->db->finishPublication($publication,$receipt['commit']);}catch(\Throwable $e){$this->db->failPublication($publication);throw $e;}return ['slug'=>$publication['slug'],'url'=>$this->settings['APP_ORIGIN'].'/'.$publication['slug'],'status'=>'published','githubCommit'=>$receipt['commit']];}
 }
 if($method==='POST'&&preg_match('~^/public/(quiz-[1-9][0-9]{0,8})/sessions$~D',$path,$m)){Domain::object($input,[]);if(!$visitor)throw new ApiError(400,'Habilite os cookies para responder.');$p=$this->db->publication($m[1]);$q=$this->db->quiz($p['quiz_id'],$p['owner_id']);return $this->newSession($q,decode($p['live_json']),'live',$visitor,$p['id']);}
 if(preg_match('~^/sessions/([a-f0-9-]+)(?:/(actions|lead))?$~D',$path,$m)){$row=$this->db->session($m[1],$owner,$visitor);$snapshot=decode($row['snapshot_json']);$state=decode($row['state_json']);$tail=$m[2]??'';if(!$tail&&$method==='GET')return Domain::view($row['id'],(int)$row['version'],$snapshot,$state);
  if($method==='POST'&&in_array($tail,['actions','lead'],true)){Domain::integer($input['version']??null,0,100000);if($input['version']!==(int)$row['version'])throw new ApiError(409,'A sessão mudou. Atualize antes de continuar.');if($tail==='actions')return $this->db->saveState($row,Domain::action($snapshot,$state,$input));$contact=Domain::contact($input);$next=Domain::complete($snapshot,$state);return $this->db->transaction(function()use($row,$snapshot,$next,$contact){$view=$this->db->saveState($row,$next);if($row['mode']==='live'){$answers=Domain::answers($snapshot,$next);$this->db->query('INSERT INTO qa_leads (id,owner_id,quiz_id,session_id,name,email,phone,consent_text,answers_json,score,result_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)',[Domain::id(),$row['owner_id'],$row['quiz_id'],$row['id'],$contact['name'],$contact['email'],$contact['phone'],$snapshot['consent'],encode($answers),$view['score'],$view['stageId'],Domain::now()]);}return $view;});}
 }
 throw new ApiError(404,'Recurso não encontrado.');
 }
}
