<?php
declare(strict_types=1);
namespace QuizAdv;
final class Store {
 public function __construct(public \PDO $pdo){$pdo->setAttribute(\PDO::ATTR_ERRMODE,\PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE,\PDO::FETCH_ASSOC);if($pdo->getAttribute(\PDO::ATTR_DRIVER_NAME)==='mysql')$pdo->setAttribute(\PDO::ATTR_EMULATE_PREPARES,false);}
 public function query(string $sql,array $values=[]):\PDOStatement {$statement=$this->pdo->prepare($sql);$statement->execute($values);return $statement;}
 public function one(string $sql,array $values=[]):?array {return $this->query($sql,$values)->fetch()?:null;}
 public function all(string $sql,array $values=[]):array {return $this->query($sql,$values)->fetchAll();}
 public function transaction(callable $fn):mixed {$this->pdo->beginTransaction();try{$result=$fn();$this->pdo->commit();return $result;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
 public function lock():string {return $this->pdo->getAttribute(\PDO::ATTR_DRIVER_NAME)==='mysql'?' FOR UPDATE':'';}
 public function quiz(string $id,string $owner):array {$row=$this->one('SELECT * FROM qa_quizzes WHERE id = ? AND owner_id = ?',[Domain::uuid($id),$owner]);if(!$row)throw new ApiError(404,'Quiz não encontrado.');return $row;}
 public function publication(string $slug):array {$row=$this->one('SELECT * FROM qa_publications WHERE slug = ? AND active = 1',[Domain::slug($slug)]);if(!$row)throw new ApiError(404,'Quiz não publicado.');return $row;}
 public function session(string $id,string|null $owner,string|null $visitor):array {$row=$this->one('SELECT s.* FROM qa_sessions s JOIN qa_quizzes q ON q.id = s.quiz_id AND q.owner_id = s.owner_id WHERE s.id = ?',[Domain::uuid($id)]);if(!$row)throw new ApiError(404,'Sessão não encontrada.');if($row['mode']==='test'){if(!$owner||!hash_equals($row['owner_id'],$owner))throw new ApiError(404,'Sessão não encontrada.');}elseif(!$visitor||!hash_equals($row['visitor_hash'],$visitor))throw new ApiError(404,'Sessão não encontrada.');if((int)$row['expires_at']<Domain::now())throw new ApiError(410,'Sessão expirada. Inicie o quiz novamente.');return $row;}
 public function rate(string $key,int $limit,int $window):void {$bucket=hash('sha256',$key.'|'.intdiv(time(),$window));$this->transaction(function()use($bucket,$limit,$window){$insert=$this->pdo->getAttribute(\PDO::ATTR_DRIVER_NAME)==='mysql'?'INSERT IGNORE':'INSERT OR IGNORE';$this->query($insert.' INTO qa_rate_limits (id,bucket_key,hits,expires_at) VALUES (?,?,?,?)',[Domain::id(),$bucket,0,time()+$window*2]);$row=$this->one('SELECT id,hits FROM qa_rate_limits WHERE bucket_key = ?'.$this->lock(),[$bucket]);if((int)$row['hits']>=$limit)throw new ApiError(429,'Muitas tentativas. Aguarde e tente novamente.');$this->query('UPDATE qa_rate_limits SET hits = hits + 1 WHERE id = ?',[$row['id']]);});}
 public function saveState(array $row,array $state):array {$updated=$this->query('UPDATE qa_sessions SET state_json = ?, version = version + 1 WHERE id = ? AND owner_id = ? AND version = ?',[encode($state),$row['id'],$row['owner_id'],(int)$row['version']]);if($updated->rowCount()!==1)throw new ApiError(409,'A sessão mudou. Atualize antes de continuar.');return Domain::view($row['id'],(int)$row['version']+1,decode($row['snapshot_json']),$state);}
 public function reservePublication(string $quizId,string $owner,int $version,array $config):array {return $this->transaction(function()use($quizId,$owner,$version,$config){$quiz=$this->one('SELECT * FROM qa_quizzes WHERE id = ? AND owner_id = ?'.$this->lock(),[Domain::uuid($quizId),$owner]);if(!$quiz)throw new ApiError(404,'Quiz não encontrado.');if((int)$quiz['version']!==$version)throw new ApiError(409,'O quiz mudou. Salve novamente.');$old=$this->one('SELECT * FROM qa_publications WHERE quiz_id = ? AND owner_id = ?'.$this->lock(),[$quizId,$owner]);if($old&&!empty($old['job_id'])&&(int)$old['job_started_at']>Domain::now()-120000)throw new ApiError(409,'Este quiz já está sendo publicado. Aguarde.');$job=Domain::id();if($old){$this->query('UPDATE qa_publications SET pending_json = ?, job_id = ?, job_started_at = ?, last_error = NULL WHERE id = ? AND owner_id = ?',[encode($config),$job,Domain::now(),$old['id'],$owner]);return [...$old,'job_id'=>$job,'pending_json'=>encode($config)];}
 $counter=$this->one('SELECT * FROM qa_counters WHERE counter_name = ?'.$this->lock(),['public_quiz']);if(!$counter)throw new ApiError(503,'Execute a instalação do banco antes de publicar.');$number=(int)$counter['next_value'];if($number>999999999)throw new ApiError(503,'Limite de endereços atingido.');$this->query('UPDATE qa_counters SET next_value = next_value + 1 WHERE id = ?',[$counter['id']]);$id=Domain::id();$slug='quiz-'.$number;$this->query('INSERT INTO qa_publications (id, quiz_id, owner_id, slug, active, live_json, pending_json, job_id, job_started_at, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',[$id,$quizId,$owner,$slug,0,null,encode($config),$job,Domain::now(),Domain::now()]);return ['id'=>$id,'quiz_id'=>$quizId,'owner_id'=>$owner,'slug'=>$slug,'job_id'=>$job,'pending_json'=>encode($config),'active'=>0];});}
 public function finishPublication(array $publication,string $commit):void {$changed=$this->query('UPDATE qa_publications SET live_json = pending_json, pending_json = NULL, active = 1, job_id = NULL, github_commit = ?, published_at = ?, last_error = NULL WHERE id = ? AND owner_id = ? AND job_id = ?',[$commit,Domain::now(),$publication['id'],$publication['owner_id'],$publication['job_id']]);if($changed->rowCount()!==1)throw new ApiError(409,'Outra publicação foi iniciada. Confira o estado do quiz.');}
 public function failPublication(array $publication):void {$this->query('UPDATE qa_publications SET job_id = NULL, last_error = ? WHERE id = ? AND owner_id = ? AND job_id = ?',['Falha no envio ao GitHub.',$publication['id'],$publication['owner_id'],$publication['job_id']]);}
}
function store():Store {static $db=null;if($db)return $db;$c=config();foreach(['DB_HOST','DB_NAME','DB_USER'] as $key)if(empty($c[$key]))throw new ApiError(503,'Configure o banco de dados na Hostinger.');if(!preg_match('/^[a-zA-Z0-9_]+$/D',$c['DB_NAME']))throw new ApiError(503,'Nome de banco inválido.');$port=(int)($c['DB_PORT']??3306);return $db=new Store(new \PDO('mysql:host='.$c['DB_HOST'].';port='.$port.';dbname='.$c['DB_NAME'].';charset=utf8mb4',$c['DB_USER'],$c['DB_PASSWORD']??'',[\PDO::ATTR_EMULATE_PREPARES=>false]));}

